// Gallery images configuration for static export
// This file is auto-generated by generateGalleryConfig.js
// Last updated: 2025-09-17T05:31:46.195Z

export const galleryImages = [
  {
    "src": "/images/gallery/IMG-20250917-WA0003.jpg",
    "alt": "PKS Capital Office Meeting",
    "category": "Office"
  },
  {
    "src": "/images/gallery/IMG-20250917-WA0004.jpg",
    "alt": "Team Collaboration Session",
    "category": "Team"
  },
  {
    "src": "/images/gallery/IMG-20250917-WA0005.jpg",
    "alt": "Financial Advisory Meeting",
    "category": "Finance"
  },
  {
    "src": "/images/gallery/IMG-20250917-WA0006.jpg",
    "alt": "Strategic Planning Discussion",
    "category": "Strategy"
  },
  {
    "src": "/images/gallery/IMG-20250917-WA0007.jpg",
    "alt": "Client Presentation",
    "category": "Presentation"
  },
  {
    "src": "/images/gallery/new_paper_publications.jpg",
    "alt": "News Paper Publications",
    "category": "Media"
  }
];

// Get all unique categories from the images
export const getCategories = () => {
  const categories = ["All", ...new Set(galleryImages.map(img => img.category))];
  return categories;
};

// Get images by category
export const getImagesByCategory = (category) => {
  if (category === "All") {
    return galleryImages;
  }
  return galleryImages.filter(img => img.category === category);
};
